version: '3'
services: 
    web:
        image: nginx:1.13
        volumes:
            - ./web:/usr/share/nginx/html
        ports:
            - 8082:80
    classification:
        image: python:3
        volumes:
            - ./app:/app
        working_dir: /app
        command: bash ./classification.sh
        ports:
            - 8080:8080
    predict:
        image: python:3
        volumes:
            - ./app:/app
        working_dir: /app
        command: bash ./predict.sh
        ports:
            - 8081:8081